; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = Firmware
default_envs = prusa_rambo
include_dir = Firmware

[env:mega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags = -std=c++17 -Wall -Wextra -Wno-expansion-to-defined -Wsign-compare -w -Os -Wl,-u,vfprintf -lprintf_flt -lm -ffunction-sections -fdata-sections -Wl,--gc-sections -flto -fno-fat-lto-objects

[env:prusa_rambo]
board = prusa_rambo
platform = atmelavr
framework = arduino
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags = -std=c++17 -Wall -Wextra -Wno-expansion-to-defined -Wsign-compare -w -Os -Wl,-u,vfprintf -lprintf_flt -lm -ffunction-sections -fdata-sections -Wl,--gc-sections -flto -fno-fat-lto-objects
; -w -Os -Wl,-u,vfprintf -lprintf_flt -lm -Wl,--gc-sections
